package jp.zuikou.system.redditprojectsample1.domain.model

import java.util.*

data class PostEntity (
    val allAwardings: List<AllAwardingEntity?>?,
    val allowLiveComments: Boolean?,
    val approvedAtUtc: Long?,
    val archived: Boolean?,
    val author: String?,
    val authorFullname: String?,
    val canGild: Boolean?,
    val canModPost: Boolean?,
    val category: Any?,
    val clicked: Boolean?,
    val contentCategories: Any?,
    val contestMode: Boolean?,
    val created: Date = Date(),
    val createdUtc: Date = Date(),
    val discussionType: Any?,
    val distinguished: String?,
    val domain: String?,
    val downs: Int?,
    //val edited: Boolean?,
    val gilded: Int?,
    val hidden: Boolean?,
    val hideScore: Boolean?,
    val remoteId: String?,
    val isCrosspostable: Boolean?,
    val isMeta: Boolean?,
    val isOriginalContent: Boolean?,
    val isRedditMediaDomain: Boolean?,
    val isRobotIndexable: Boolean?,
    val isSelf: Boolean?,
    val isVideo: Boolean?,
    val likes: Any?,
    val locked: Boolean?,
    val media: Any?,
    val mediaOnly: Boolean?,
    val name: String?,
    val noFollow: Boolean?,
    val numComments: Int?,
    val numCrossposts: Int?,
    val numReports: Any?,
    val over18: Boolean?,
    val parentWhitelistStatus: String?,
    val permalink: String?,
    val pinned: Boolean?,
    val pwls: Int?,
    val quarantine: Boolean?,
    val removalReason: Any?,
    val reportReasons: Any?,
    val saved: Boolean?,
    val score: Int?,
    val selftext: String?,
    val selftextHtml: String?,
    val sendReplies: Boolean?,
    val spoiler: Boolean?,
    val stickied: Boolean?,
    val subreddit: String?,
    val subredditId: String?,
    val subredditNamePrefixed: String?,
    val subredditSubscribers: Int?,
    val subredditType: String?,
    val suggestedSort: Any?,
    val thumbnail: String?,
    val title: String?,
    val totalAwardsReceived: Int?,
    val ups: Int?,
    val url: String?,
    val viewCount: Any?,
    val visited: Boolean?,
    val whitelistStatus: String?,
    val wls: Int?,
    val imagePreview: List<ImageEntity>? = null
    )